[package]
name = "arbitrage-scanner"
version = "1.0.0"
edition = "2021"

[dependencies]
ethers = "2.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"